# docker-compose.yml
version: '3'
services:
    tylosql:
        image: postgres
        environment:
            POSTGRES_USER: tylosaur
            POSTGRES_PASSWORD: secret
            POSTGRES_DB: tylosaur
        ports:
            - 5432:5432
        volumes:
        - database-data:/var/lib/postgresql/data/
    adminer:
        image: adminer
        restart: always
        ports:
            - 8080:8080
volumes:
  database-data: